### ISSUE TITLE
About calculating confidence

### ISSUE THREAD

**Issue by cduej** [giuliomattolin/ConfMix#18]
Can you tell me where the code for confidence calculation is？The formula in the paper is as follows.

C = (1 − δ) · Cdet + δ · Ccomb

**Comment by giuliomattolin** [comment]
Hi @cduej,

Here in the forward of the model: https://github.com/giuliomattolin/ConfMix/blob/f4c0ef3c385f103597537e8b4d7624601732b2b3/models/yolo.py#L86

**Comment by cduej** [comment]
Sorry.Can you tell me how did you get ’Gaussian-based bounding box‘? Can you tell me where the code for this?
b = [µbx, µby, µbh, µbw, Σbx, Σby, Σbh, Σbw]
