### ISSUE TITLE
Some questions about the README

### ISSUE THREAD

**Issue by HDUyiming** [giuliomattolin/ConfMix#2]
I find some issues in your README:
**firstly**，**the yaml data in your "Phase 1: Model pre-train/Cityscapes -> Foggy Cityscapes:" is not same with the yaml data in"Phase 2: Adaptive learning/Cityscapes -> Foggy Cityscapes:",i.e. "--data data/Cityscapes2FoggyCityscapes.yaml \" and "--data data/Cityscapes2Foggy.yaml \",should these tow yaml be the same?
**secondly**,is there a mistake of the yami data in "Phase 2: Adaptive learning/Sim10k -> Cityscapes (car category only):"? the yaml's name is/Cityscapes2Foggy.yaml
Thank you so much for sharing your paper and code!

**Comment by giuliomattolin** [comment]
Hi @HDUyiming,

As you correctly pointed out, some names of the `.yaml` files related to the `--data` parameter were incorrect.
The README has now been updated with the correct names and you should be able to perform the training without problems.

Thank you for your valuable feedback!

**Comment by HDUyiming** [comment]
You're welcome. I really appreciate your work, too. I just came into contact with the field of object detection in UDA, and happened to see your paper in the search, which helped me a lot in my study, thank you again!

从 Windows 版邮件发送

发件人: Giulio Mattolin
发送时间: 2022年11月23日 20:51
收件人: giuliomattolin/ConfMix
抄送: HDUyiming; Mention
主题: Re: [giuliomattolin/ConfMix] Some questions about the README (Issue#2)

Hi @HDUyiming,
As you correctly pointed out, some names of the .yaml files related to the --data parameter were incorrect.
The README has now been updated with the correct names and you should be able to perform the training without problems.
Thank you for your valuable feedback!
