### ISSUE TITLE
Variation in the reproduced results

### ISSUE THREAD

**Issue by manan-d8** [giuliomattolin/ConfMix#23]
Hello,

I ran your code and attempted to replicate it five times. Each time, I noticed quite a bit of variation in the training results. Even in the last epoch, there was around a 5mAP difference. I just wanted to check if this level of variance during training is expected or normal.

Please find this info about the training for your reference (last mAP).

- **Experiment: Sim10k2cityscapes**
> Run 1 | 55.76 mAP
> Run 2 | 54.33 mAP
> Run 3 | 53.81 mAP
> Run 4 | 53.12 mAP
> Run 5 | 51.90 mAP

**Thanks in advance.**

**Comment by giuliomattolin** [comment]
Hi Manan,

Unfortunately, there is always some degree of randomness in each run, even when all seeds are set (https://pytorch.org/docs/stable/notes/randomness.html). We have also observed that different runs gave different results, although these variations were usually not that substantial. If I have to give a guess, it could be that during an unfortunate run, if the model predicts an inaccurate pseudo-detection, it influences the model performance and all the subsequent pseudo-detections on which it will be trained, creating a cascading effect and impacting the model's performance in future iterations.

**Comment by manan-d8** [comment]
Hi Giulio,

I'm really grateful for your quick response. Could you possibly share what can be considered a normal range of mAP variation across different runs? It would be incredibly helpful if you could provide a range.

**Thanks a lot.**

**Comment by giuliomattolin** [comment]
I worked on this paper during an internship 2 years ago, I don't have access anymore to the files of the runs unfortunately.
