### ISSUE TITLE
Issues Regarding UDA Weights

### ISSUE THREAD

**Issue by vioolettaah** [giuliomattolin/ConfMix#25]
Hello @giuliomattolin , my partner and I are trying to implement your code for pothole detection, and have managed to pre-train the models. However, we weren't able to find the suitable .pt file that is supposed to be the weights for UDA. We've tried looking for it in ConfMix/runs/train folder, but to no avail. Is the .pt file supposed to show up once the pre-training code is run? If so, in which directory are we supposed to look for the file? and if not, are there any additional steps that we're missing in order to obtain the .pt file? Thank you in advance!

**Comment by giuliomattolin** [comment]
Hi @vioolettaah,

If you have not modified this line https://github.com/giuliomattolin/ConfMix/blob/f4c0ef3c385f103597537e8b4d7624601732b2b3/train.py#L508 the model should be in the runs/train inside the folder of the run. Do you have the runs/train folder? Are there folders inside it?

**Comment by vioolettaah** [comment]
No, we haven't made any changes to the training code, but yes, the runs/train folder is there, with what I presume is our pre-trained model (potholeAtoB). However, as you can see in the image below, the weight folder (which is where I believe the .pt file should be) is empty.
![image](https://github.com/giuliomattolin/ConfMix/assets/171562827/f31cc33b-51c7-4352-883f-159ab7dd97e3)
Apologies if our question seems rather trivial, but we really appreciate the fast response!

**Comment by giuliomattolin** [comment]
Have you finished all the epochs in the training? The model is saved at the end of the last epoch, I suggest to try to start the training with 1 epoch, reach the end of the training and check the folder. If there is nothing still, I suggest to debug the code, especially inside here: https://github.com/giuliomattolin/ConfMix/blob/f4c0ef3c385f103597537e8b4d7624601732b2b3/train.py#L417
