### ISSUE TITLE
Some problems of training and Val

### ISSUE THREAD

**Issue by HDUyiming** [giuliomattolin/ConfMix#3]
hi Giulio,I have met some difficulties and hope you can help me. Thank you.

**1. When I run your code, both `train.py `and `uda_train.py `result in very small mAP values, the result of 20 epoch pre_train as follows:**

![result](https://user-images.githubusercontent.com/118901569/205202861-002c945b-e371-4b4b-bf48-f66b25559fde.png)

**2. When I run` uda_val.py`, I get an error:**

> TypeError: forward() got an unexpected keyword argument 'pseudo'

So I think something is wrong on line 438 of `common.py` 
There is also a problem with the number of functions returned:

> return (y, []) if val else y  (common.py 494)
out, train_out, var = model(im, pseudo=True) if training else model(im, augment=augment, val=True, pseudo=True)  # inference, loss outputs(uda_val.py 206)

I really hope the author can help me solve these problems,thank you very much!

**Comment by AmrinKareem** [comment]
Hi @giuliomattolin thank you for your work. @HDUyiming, I am facing the same issue as yours - train.py results in very small mAP values - Could you please share how you solved the issue? Here is a screenshot of my epochs: Thank you in advance :)

![image](https://user-images.githubusercontent.com/43820644/232917718-be8145b7-d64b-4444-92ba-a2dd85575924.png)

**Comment by giuliomattolin** [comment]
Hi @AmrinKareem,

If you are running the Cityscapes2Foggy benchmark, make sure to use only images with $\beta$ = 0.02, **both** in the training and validation sets. From the screenshot, you posted I see that there are 1500 images in the validation set, while there should be only 500, which is the amount of validation images having $\beta$ = 0.02.

I hope this will help you!
