### ISSUE TITLE
  File "/paper_code/ConfMix-master/uda_val.py", line 206, in run     out, train_out, var = model(im, pseudo=True) if training else model(im, augment=augment, val=True, pseudo=True)  # inference, loss outputs   File "/usr/local/miniconda3/envs/ConfMix/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl     result = self.forward(*input, **kwargs) TypeError: forward() got an unexpected keyword argument 'pseudo'

### ISSUE THREAD

**Issue by jzpcn** [giuliomattolin/ConfMix#6]
I just met this problem, who can help me?

**Comment by jzpcn** [comment]
File "/paper_code/ConfMix-master/uda_val.py", line 206, in run
    out, train_out, var = model(im, pseudo=True) if training else model(im, augment=augment, val=True, pseudo=True)  # inference, loss outputs
ValueError: not enough values to unpack (expected 3, got 2)

And when I change the parameter of forwrad , it met this problem.

**Comment by giuliomattolin** [comment]
Hi @jzpcn,

To solve this problem, you can refer to Closed Issue #3.
Nevertheless, today I will push the code to fix this error.

**Comment by giuliomattolin** [comment]
Hi @jzpcn,

I have pushed the fix to this error.
You can now pull the new code and it should work :)

**Comment by jzpcn** [comment]
Hi, @giuliomattolin,

Thanks for your answer.
It works fine when using the new code!
